### ISSUE TITLE
Paginate with collections

### ISSUE THREAD

**Issue by ariews** [morgan/kohana-paginate#3]
Hi,

This is a question rather than a bugs :)

With kohana-paginate, can I do something like this ( get all posts with 'news' tag)?

```
$tag = ORM::factory('tag', 5); // news tag
$articles = $tag->articles; // articles with news' tag

$paginate = Paginate::factory($articles);
```

I try the above code, but didn't work

Thanks.

**Comment by morgan** [comment]
Hello,

Thank you for your interest in Paginate.

If you have your ORM relationship setup and Paginate properly implemented, it should work as expected. The important factor here is that Paginate is provided an ORM object prior to `ORM::find` or `ORM::find_all` being called.

Looking at the `has_many` relationship within ORM, it appears to simply perform the database operations on the object and return the object prior to `ORM::find_all`. https://github.com/kohana/orm/blob/3.2/master/classes/kohana/orm.php#L617

In the end, using the `has_many` relationship should be no different than:

``` php
$tag = ORM::factory('tag', 5);

$articles = ORM::factory('article')
    ->where('tag_id', '=', $tag->id);

$paginate = Paginate::factory($articles)
    ->columns(array('title', 'created_at'));
```

If you're relationship is not setup correctly, it could be performing a `ORM::find` which would certainly affect the operation.

Additionally, make sure Paginate is properly implemented as prescribed by the documentation: http://dev.morgan.ly/kohana/v3.2/guide/paginate/start

Please let me know if you have any questions or run into any issues while debugging your setup.

Thank you,

Micheal Morgan

**Comment by ariews** [comment]
Thanks, this is great. especialy when combine with kohana-datatables.

**Comment by morgan** [comment]
Thank you for the kind words. I have this module implemented using Database, ORM, REST and ORM-REST. Feel free to reach back out if you have any questions or feedback.

Thanks again.
