### ISSUE TITLE
GROUP BY CASE issue

### ISSUE THREAD

**Issue by erralb** [morgan/kohana-paginate#7]
Hi and sorry to bother you again :)

I'm trying to use paginate with this query : 

``` php
$products = DB::query(Database::SELECT, '
            SELECT * FROM shop_products
            GROUP BY CASE configurable 
            WHEN 1 THEN configuration_id
            ELSE id 
            END
        ')->as_object('Model_Product');
```

I have to go through a manual query because ORM does not support the group by case condition.

The thing is, DB::query() returns a Database_Query object which (logically) does not implement the order_by() and the offset() functions, so I'm getting this error : Call to undefined method Database_Query::order_by() in /modules/paginate/classes/Kohana/Paginate/Database.php on line 64

Would you have an idea to work around this problem? Right now the only way I can see this working, is to actually write a group_by_case function for the database query builder class, but I thought you might have another idea...?

**Comment by morgan** [comment]
No bother!

I recommend trying to stick with the query builder and working with expressions to get your desired result. You might need to reconsider your query anyway, regardless of how it is executed, for applying additional filtering clauses. However, to get you started, below is an approach for using database builder with an expression: 

``` php
$expression = DB::expr('CASE configurable 
    WHEN 1 THEN configuration_id
    ELSE id 
    END');

$builder = DB::select()
    ->from('shop_products')
    ->group_by($expression);

echo debug::vars((string) $db);
```

This results in:

``` sql
SELECT * FROM `shop_products` GROUP BY CASE configurable 
WHEN 1 THEN configuration_id
ELSE id 
END
```

Please let me know if this does the trick.

Cheers!

**Comment by erralb** [comment]
Hey thanks for the answer!

I'm actually already using DB expressions but looking at the groupy_by() function, I don't know why, I just didn't think it'd work, and I didn't even try...
Your solution is working thanks! 
At the end I even use it directly with the ORM : 

``` php
$expression = DB::expr('
  CASE configurable 
  WHEN 1 THEN configuration_id
  ELSE id 
  END');
$products =  ORM::factory('Product')->group_by($expression);
```

Sorry for stackoverflowing.com your repo :)

**Comment by morgan** [comment]
Keep in mind that database builder fairly cleverly casts parameters to strings which creates a neat cascading effect. When `DB::expr` object is casted to a string, it's converted into SQL. Therefore, pretty much across the board this concept works and allows for using the database builder fairly broadly.

**Comment by erralb** [comment]
Yes now I see that, thanks for the explanation!
